# Generated by Django 5.0.4 on 2025-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.PositiveIntegerField()),
                ('gambar', models.ImageField(upload_to='menu_images/')),
            ],
        ),
    ]
